[examples.sat.hillclimb] Fix required failure probability per round
qubrabench/qubrabench pull request #85
Opened 2023-07-19 14:48 UTC by anurudhp

fixes #52

2023-07-19 15:06 UTC, catch22 commented on examples/sat/hillclimber.py
> +    if error is not None:
you could simplify this as
```
if error is not None:
  error /= n
```

2023-07-19 15:07 UTC, catch22 requested changes
This PR aims to fix #52, but I believe the following two items still need work before this PR can be merged:
- [x] Verify quantum statistics anew (compare with existing reference data and papers)
- [ ] Check steep hillclimber statistics

2023-07-25 09:49 UTC, timbittner commented on examples/sat/hillclimber.py
> +    if error is not None:
did this

2023-07-25 09:50 UTC, timbittner commented
As far as I can tell steep works if the quantum factor is set to `1`, see attached image.
![hillclimber_speed_quantumfactor1](https://github.com/qubrabench/qubrabench/assets/56638681/35f8232f-a584-4729-8b38-1fc76e58fd35)

2023-07-25 11:57 UTC, catch22 commented
(See Slack)

2023-07-25 22:34 UTC, merged